/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2023-09-06 07:35:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Exweb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let cate1 = [\"의류\", \"가전\", \"컴퓨터\"];\r\n");
      out.write("let cate2 = [[\"여성복\", \"남성복\", \"아동복\"], [\"TV\",\"세탁기\",\"냉장고\"], [\"데스크탑\", \"노트북\", \"주변기기\"]];\r\n");
      out.write("let cate3 = [[[\"원피스\",\"투피스\"], [\"셔츠\",\"바지\",\"남방\"],[\"내복\", \"우주복\"]],\r\n");
      out.write("	[[\"LG TV\",\"삼성TV\",\"중소TV\"],[\"LG세탁기\",\"삼성세탁기\",\"중소 세탁기\"],[\"LG냉장고\",\"삼성냉장고\",\"중소냉장고\"]],\r\n");
      out.write("	[[\"LG데스크탑\",\"삼성데스크탑\",\"중소 데스크탑\"],[\"LG노트북\",\"삼성노트북\",\"중소노트북\"],[\"프린터\",\"스피커\",\"마이크\"]]];\r\n");
      out.write("\r\n");
      out.write("window.onload = () => {\r\n");
      out.write("	let txt = \"<table style='background-clolr:gray' border='1'>\";\r\n");
      out.write("	for(let s of cate1){\r\n");
      out.write("		txt += \"<tr><td style='width:100px; height:40px'>\" + s + \"</td></tr>\";\r\n");
      out.write("	}\r\n");
      out.write("	txt +=\"</table>\";\r\n");
      out.write("	let e1 = document.getElementById(\"cate1\");\r\n");
      out.write("	e1.innerHTML = txt;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("const cf = (idx) => {\r\n");
      out.write("	alter(cate2[idx].toString());\r\n");
      out.write("}\r\n");
      out.write("const a = () => {\r\n");
      out.write("	let el =  document.getElementById(\"cate1\");\r\n");
      out.write("	e1.style.display='';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("const b = () => {\r\n");
      out.write("	let e1 = document.getElementById(\"cate1\");\r\n");
      out.write("	e1.style.display='none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"cate1\" style='position: absolute; top: 140px; left: 10px; display: none' onmouseover=\"a()\"></div>\r\n");
      out.write("	<div id=\"cate2\" style='position: absolute; top: 140px; left: 10px; display: none' onmouseover=\"b()\"></div>\r\n");
      out.write("	<div id=\"cate3\" style='position: absolute; top: 140px; left: 10px; display: none' onmouseover=\"a()\"></div>\r\n");
      out.write("	\r\n");
      out.write("	<table border=\"1\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td style=\"width: 700px; height: 200px\">\r\n");
      out.write("				<div id=\"cate\" style=\"width:70px;height:70px; background-color:yellow; border: 1px solid black\" onmouseover=\"a()\" onmouseout=\"b()\">\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<img style=\"width:700px; height:180px;\"src=\"https://cataas.com/cat/gif\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td style=\"width: 700px; height: 500px\">\r\n");
      out.write("				<div id=\"content\"></div>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
